apiVersion: apps/v1
kind: Deployment
metadata:
  name: jitsi-jicofo
  namespace: jitsi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jitsi-jicofo
  template:
    metadata:
      labels:
        app: jitsi-jicofo
    spec:
      containers:
        - name: jicofo
          image: 17082002/jitsi_meet_app:jicofo
          envFrom:
            - secretRef:
                name: jitsi-secret-env
---
apiVersion: v1
kind: Service
metadata:
  name: jitsi-jicofo
  namespace: jitsi
spec:
  selector:
    app: jitsi-jicofo
  ports:
    - port: 8888
      targetPort: 8888

